---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: busybox-account
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    app: busybox1
spec:
  serviceAccountName: busybox-account
  containers:
  - image: curlimages/curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
